# Generated by Django 3.2.6 on 2021-10-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_userproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='order_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
