# Generated by Django 3.2.6 on 2021-10-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20211031_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldbook',
            name='bookimage',
            field=models.FileField(default='', upload_to='uploads/files'),
        ),
    ]
