# Generated by Django 3.2.6 on 2021-10-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('FAIL', 'FAIL'), ('SUCCESS', 'SUCCESS')], max_length=40),
        ),
        migrations.AlterField(
            model_name='soldbook',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
