# Generated by Django 3.2.6 on 2021-10-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_soldbook_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAIL', 'FAIL')], max_length=40),
        ),
        migrations.AlterField(
            model_name='soldbook',
            name='sold_id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
