# Generated by Django 3.2.6 on 2021-10-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20211031_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldbook',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='soldbook',
            name='sold_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
