# Generated by Django 3.2.6 on 2021-10-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldbook',
            name='description',
            field=models.TextField(default=True, max_length=6000),
        ),
    ]
